apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow

name: RetirementPro - Build Evidence

on:
  push:
    branches:
      - master

permissions:
  scm-token-own: read
  id-token: write

jobs:
  build-evidence:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
          
      - name: Publish Build Evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |
            ## 🏗️ Build Jenkins (CloudBees CI)
            
            **Pipeline**: lsa/RetirementProFolder/build/master
            **Controller**: https://core.cloudbees.guru/shared-demos
            **Agent**: Kubernetes Pod (Maven 3.9.5 + JDK 17)
            **Commit**: ${{ cloudbees.scm.sha }}
            **Branch**: ${{ cloudbees.scm.branch }}
            
            ✅ Build triggered automatically via GitHub webhook
            ✅ Artifact archived in Jenkins
            ✅ GitHub Actions tests running in parallel
            
            **Orchestration**: 
            - Jenkins build via webhook
            - GitHub Actions tests via push trigger
            - Evidence centralized in CloudBees Platform
