apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow

name: RetirementPro - Orchestration

on:
  push:
    branches:
      - master

permissions:
  scm-token-own: read
  id-token: write

jobs:
  orchestration:
    steps:
      - name: Publish Evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |
            ## 🏗️ Build & Test Orchestration
            
            **Jenkins Build**: [View Pipeline](https://core.cloudbees.guru/shared-demos/job/lsa/job/RetirementProFolder/job/build/job/master/)
            
            **GitHub Actions Tests**: [View Workflow](https://github.com/lsa26/RetirementPro/actions/workflows/tests.yml)
            
            **Commit**: `${{ cloudbees.scm.sha }}`
            **Branch**: `${{ cloudbees.scm.branch }}`
            
            ### Orchestration
            - ✅ Jenkins: Build + Package (Kubernetes Pod)
            - ✅ GitHub Actions: Unit Tests (JUnit)
            - ✅ CloudBees Platform: Evidence & Traceability
            
            **Artifacts**: Available in Jenkins
            **Test Results**: Available in GitHub Actions
