apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow

name: RetirementPro - Build and Test

on:
  push:
    branches:
      - master

permissions:
  scm-token-own: read
  id-token: write

jobs:
  build-evidence:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
          
      - name: Publish Build Evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |
            ## 🏗️ Build Jenkins (CloudBees CI)
            
            **Pipeline**: [lsa/RetirementProFolder/build/master](https://core.cloudbees.guru/shared-demos/job/lsa/job/RetirementProFolder/job/build/job/master/)
            
            **Last Build**: [View Build](https://core.cloudbees.guru/shared-demos/job/lsa/job/RetirementProFolder/job/build/job/master/lastBuild/)
            
            **Artifact**: [retirement-api-1.0.0-SNAPSHOT.jar](https://core.cloudbees.guru/shared-demos/job/lsa/job/RetirementProFolder/job/build/job/master/lastSuccessfulBuild/artifact/target/retirement-api-1.0.0-SNAPSHOT.jar)
            
            **Details**:
            - Agent: Kubernetes Pod (Maven 3.9.5 + JDK 17)
            - Commit: `${{ cloudbees.scm.sha }}`
            - Branch: `${{ cloudbees.scm.branch }}`
            
            ✅ Build completed on CloudBees CI
            ✅ Artifact archived in Jenkins
            
  test-insights:
    needs: build-evidence
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
        
      - name: Configure Java
        uses: cloudbees-io/configure-jdk-action@v1
        with:
          version: "17"
          
      - name: Run Tests
        run: mvn test
        
      - name: Publish Test Results to Test Insights
        uses: cloudbees-io/test-reporting@v1
        with:
          test-type: JUnit
          test-results-location: '**/target/surefire-reports/*.xml'
          
      - name: Publish Test Evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |
            ## 🧪 Test Results
            
            **Test Suite**: JUnit unit tests
            **Framework**: JUnit 5 + Mockito
            **Tests**: BeneficiaryServiceTest
            
            ✅ Tests executed in CloudBees Unify
            ✅ Results published to Test Insights
            ✅ Available in Test Results tab
